# this is mandatory; as app name is appended in each log for grouping in elastic stack
app:
  name: spring-kafka-mongodb

# this is mandatory; as environment is appended in each log for grouping in elastic stack
environment: ${ENVIRONMENT}

server:
  port: 5001

spring:
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: todo
    rest:
      basePath: /api/v1

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      indent_output: true

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

  http:
    encoding:
      # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
      charset: UTF-8
      # Enable http encoding support.
      enabled: true
      # Force the encoding to the configured charset on HTTP requests and responses.
      force: true

todo:
  kafka:
    producer:
      bootstrap: ${KAFKA_CLUSTER}
      group: todo-consumer
      todoTopic: todo