# this is mandatory; as environment is appended in each log for grouping in elastic stack
environment: ${ENVIRONMENT:dev}

server:
  port: 5001

spring:
  application:
    name: store
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: todo
    rest:
      basePath: /api/v1

  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      indent_output: true

  mvc:
    throw-exception-if-no-handler-found: true

  http:
    encoding:
      # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
      charset: UTF-8
      # Enable http encoding support.
      enabled: true
      # Force the encoding to the configured charset on HTTP requests and responses.
      force: true


todo:
    kafka:
        bootstrap-servers: ${KAFKA_CLUSTER:localhost}
        todo-topic: todo

endpoints:
    env:
        enabled: true
        sensitive: false # not good idea!
    health:
        enabled: true
        sensitive: false

# TODO enable & get rid of it - full authentication is required to access actuator endpoints. Consider adding Spring Security or set 'management.security.enabled' to false.
management:
    security:
        enable: false
