version: '2'

services:
    todostore-app:
        image: todostore
        container_name: store
        labels:
            - "SERVICE_NAME=store"
        environment:
            - ENVIRONMENT=dev
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - MONGODB_HOST=mongo
            - MONGODB_PORT=27017
            - KAFKA_CLUSTER=kafka:9092
        depends_on:
            - registrator
            - registrator2
        ports:
            - 8085:8080

    todogateway-app:
        image: todogateway
        container_name: gateway
        labels:
            - "SERVICE_NAME=gateway"
        environment:
            - ENVIRONMENT=dev
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
        depends_on:
            - registrator
            - registrator2
        ports:
            - 4001:8080

    consul:
        image: consul:0.8.3
        container_name: consul
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
        command: consul agent -dev -ui -client 0.0.0.0

    consul-config-loader:
        image: stakater/consul-config-loader:latest
        container_name: consul-config-loader
        labels:
            - "SERVICE_NAME=consul-config-loader"
        volumes:
            - ../../../../config/:/config
        links:
            - consul
        environment:
            - CONFIG_MODE=git
            - INIT_SLEEP_SECONDS=5
            - CONSUL_URL=consul

    registrator:
        image: gliderlabs/registrator:latest
        container_name: registrator
        links:
            - consul
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        command: -internal consulkv://consul:8500/config/store/service

    registrator2:
        image: gliderlabs/registrator:latest
        container_name: registrator2
        links:
            - consul
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock
        command: -internal consul://consul:8500/config/store/service

    mongo:
        container_name: mongo
        labels:
            - "SERVICE_NAME=mongo"
            - "SERVICE_ID=mongo"
        image: mongo:latest
        ports:
            - 27017:27017
        depends_on:
            - registrator
            - registrator2

    kafka:
        image: spotify/kafka
        container_name: kafka
        labels:
            - "SERVICE_NAME=kafka"
        ports:
            - 2181:2181
            - 9092:9092
        depends_on:
            - registrator
            - registrator2
