version: '2'

services:
    todostore-app:
        image: todostore
        external_links:
            - todostore-mongo:mongo
        environment:
            - ENVIRONMENT=dev
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - MONGODB_HOST=mongo
            - MONGODB_PORT=27017
        ports:
            - 8085:8080

    todostore-mongo:
        extends:
            file: mongo.yml
            service: todostore-mongo

    consul:
        image: consul:0.8.3
        container_name: consul
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
        command: consul agent -dev -ui -client 0.0.0.0

