version: '2'

services:
    consul:
        image: consul:0.8.3
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
        command: consul agent -dev -ui -client 0.0.0.0

    kafka:
        image: spotify/kafka
        container_name: kafka
        ports:
            - 2181:2181
            - 9092:9092

    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - 27017:27017
