version: '2'

services:
    consul:
        image: consul:0.8.3
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
        command: consul agent -dev -ui -client 0.0.0.0

    registrator:
        image: gliderlabs/registrator:latest
        container_name: registrator
        depends_on:
            - consul
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
        command: consul://consul:8500

    kafka:
        image: spotify/kafka
        container_name: kafka
        depends_on:
            - registrator
        ports:
            - 2181:2181
            - 9092:9092
        environment:
            - ADVERTISED_HOST=localhost
            - ADVERTISED_PORT=9092

    mongo:
        image: mongo:3.4
        container_name: mongo
        depends_on:
            - registrator
        ports:
            - 27017:27017

    mysql:
        image: mysql:5.7
        container_name: mysql
        depends_on:
            - registrator
        #volumes:
        #    - "/var/data/mysql:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - "3306:3306"

    elasticsearch:
        image: stakater/elasticsearch:2.3.1
        container_name: elasticsearch
        depends_on:
            - registrator
        #volumes:
        #    - "/var/data/elasticsearch:/usr/share/elasticsearch/data"
