version: '2'

services:
    consul:
        image: consul:0.8.3
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
        command: consul agent -dev -ui -client 0.0.0.0

    registrator:
        image: gliderlabs/registrator:latest
        container_name: registrator
        depends_on:
            - consul
        volumes:
            - "/var/run/docker.sock:/tmp/docker.sock"
        command: consul://consul:8500

    kafka:
        image: spotify/kafka
        container_name: kafka
        depends_on:
            - registrator
        ports:
            - 2181:2181
            - 9092:9092
        environment:
            - ADVERTISED_HOST=localhost
            - ADVERTISED_PORT=9092

    mongo:
        image: mongo:latest
        container_name: mongo
        depends_on:
            - registrator
        ports:
            - 27017:27017
